### ISSUE TITLE
Detection fails on svg but don't know why

### ISSUE THREAD

**Issue by sam0971** [sindresorhus/is-svg#23]
is-svg returns false for the following svg:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"
[ <!ENTITY Smile "
<rect x='.5' y='.5' width='29' height='39' fill='black' stroke='red'/>
<g transform='translate(0, 5)'>
<circle cx='15' cy='15' r='10' fill='yellow'/>
<circle cx='12' cy='12' r='1.5' fill='black'/>
<circle cx='17' cy='12' r='1.5' fill='black'/>
<path d='M 10 19 A 8 8 0 0 0 20 19' stroke='black' stroke-width='2'/>
</g>
">
<!ENTITY Viewport1 "<rect x='.5' y='.5' width='49' height='29'
fill='none' stroke='blue'/>">
<!ENTITY Viewport2 "<rect x='.5' y='.5' width='29' height='59'
fill='none' stroke='blue'/>">
]>
<svg width="850px" height="700px" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
  <g transform="matrix(16,0,0,16,0,0)">
  &Smile;
  </g>
</svg>
```

It's a SVG I took from the internet, can you tell me why this is an invalid SVG?

**Comment by eluisfonseca** [comment]
The svg is valid, according to W3C standards. The issue has to do with the regex being used:

`/^\s*(?:<\?xml[^>]*>\s*)?(?:<!doctype svg[^>]*\s*(?:\[?(?:\s*<![^>]*>\s*)*\]?)*[^>]*>\s*)?(?:<svg[^>]*>[^]*<\/svg>|<svg[^/>]*\/\s*>)\s*$/i`

As it is, due to this part of the expression: `\[?(?:\s*<![^>]*>\s*)*\]` it does not allow for markup to be included in an Entity's internal subset. If you remove them, isSvg() returns `true`.

To fix this we could simply remove `>` has a forbidden character to occur inside the square brackets of the doctype tag (with the end expression being: `/^\s*(?:<\?xml[^>]*>\s*)?(?:<!doctype svg[^>]*\s*(?:\[?(?:\s*<![^]*>\s*)*\]?)*[^>]*>\s*)?(?:<svg[^>]*>[^]*<\/svg>|<svg[^/>]*\/\s*>)\s*$/i`

Or update the regex to allow for markup. I tried to come up with something. but allowing for markup would mean we would need to allow for pretty much anything. So I went with allowing any content to be added when inside double quotes. Like so:
`/^\s*(?:<\?xml[^>]*>\s*)?(?:<!doctype svg[^>]*\s*(?:\[?(?:\s*<!\s*[^]*(?:\"[^]*\")*\s*>\s*)*\]?)*[^>]*>\s*)?(?:<svg[^>]*>[^]*<\/svg>|<svg[^/>]*\/\s*>)\s*$/i`

But this would make the function even _dirtier_ as it would allow for any type of scrap to happen inside the doctype tag. Are any of these solutions viable? Any ideas? I can open a PR and address this.

**Comment by sindresorhus** [comment]
@eluisfonseca How about a regex that strips out markup from inside the entity before running the detection?

**Comment by eluisfonseca** [comment]
Good idea. So we'll do no check of the entity's content and just remove it and then just validate the what is left.  I'll look into it.
